#!/bin/sh

set -e

case "$1" in
    purge|remove|upgrade)
        initctl stop apps/messupd || true
        # Just in case Upstart could not stop the daemon, kill it    
        killall exampleappd || true        
	    ;;
								    
    failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
